In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = tf.random_normal([2,20])

In [5]:
sess = tf.Session()

In [8]:
out = sess.run(a)

In [9]:
out

array([[-0.68031961, -0.51840907, -0.53549254,  1.51236391, -0.96429133,
         0.84790844, -1.20953012, -0.44622856, -0.88163316, -0.19227636,
        -1.02810431, -0.57487798,  0.66821504, -1.61282086,  0.07543381,
        -2.17958784, -0.17637818, -0.43708581,  0.39976323,  0.60174656],
       [ 0.24393873, -2.26587367,  0.35389596,  1.21521723,  1.36715817,
         1.91565895, -1.15552366,  0.05932   , -0.13200273, -1.05747473,
         0.09699664, -1.24768674,  1.15292335,  2.32580066,  0.78415   ,
        -1.70844829, -0.14046535,  1.33002996, -0.3846308 ,  0.71822917]], dtype=float32)

In [10]:
x,y = out

In [11]:
x

array([-0.68031961, -0.51840907, -0.53549254,  1.51236391, -0.96429133,
        0.84790844, -1.20953012, -0.44622856, -0.88163316, -0.19227636,
       -1.02810431, -0.57487798,  0.66821504, -1.61282086,  0.07543381,
       -2.17958784, -0.17637818, -0.43708581,  0.39976323,  0.60174656], dtype=float32)

In [12]:
y

array([ 0.24393873, -2.26587367,  0.35389596,  1.21521723,  1.36715817,
        1.91565895, -1.15552366,  0.05932   , -0.13200273, -1.05747473,
        0.09699664, -1.24768674,  1.15292335,  2.32580066,  0.78415   ,
       -1.70844829, -0.14046535,  1.33002996, -0.3846308 ,  0.71822917], dtype=float32)

In [13]:
plt.scatter(x,y)
plt.show()